name: directory-listing
on: [push]

jobs:
  pages-directory-listing-release:
    runs-on: ubuntu-latest
    name: Directory Listings Index
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate Directory Listings
        uses: 101br03k/github-pages-directory-listing@v2.0.0
        with:
          FOLDER: documents    #directory to generate index

      - name: Deploy to Pages
        uses: 101br03k/github-pages-deploy-action@4.1.3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: documents
